name = "EntropicToy"
uuid = "64500664-983d-4783-915c-583ababcfcd4"
authors = ["Rethna Pulikkoonattu et al."]
version = "0.1.0"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[compat]
Documenter = "0.27"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
