name = "EntropicToy"
uuid = "64500664-983d-4783-915c-583ababcfcd4"
authors = ["Rethna Pulikkoonattu et al."]
version = "0.1.0"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
